#  Builds a Eureka Server "prototype" instance. I'm going to create an AMI from this, manually (for now)

- hosts: localhost
  gather_facts: no
  vars:
     region: eu-west-1
     keypair_name: microservice-course-keypair
     security_group_name: eureka-server-security-group
     instance_type: t2.nano
     image_name: ami-70edb016

  tasks:
    - name: Setup security group
      ec2_group:
        name: "{{ security_group_name }}"
        description: Security rules for Eureka Server
        region: "{{ region }}"
        rules_egress:
            - proto: tcp
              from_port: 0
              to_port: 65535
              cidr_ip: 0.0.0.0/0
        rules:
           - proto: tcp
             from_port: 8010
             to_port: 8010
             cidr_ip: 0.0.0.0/0

           - proto: tcp
             from_port: 22
             to_port: 22
             cidr_ip: 0.0.0.0/0

    - name: Provision an instance
      ec2:
        key_name: "{{ keypair_name }}"
        group: "{{ security_group_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image_name }}"
        wait: true
        region: "{{region}}"
        exact_count: 1
        count_tag:
          Name: Eureka_Server
        instance_tags:
          Name: Eureka_Server
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: "{{ec2.instances}}"

    - name: Wait for SSH Server to start responding
      wait_for:
              port: 22
              host: "{{item.public_ip}}"
              state: started
      with_items: "{{ec2.instances}}"

- hosts: tag_Name_Eureka_Server ec2hosts
  tasks:
  - name: upgrade all packages
    yum: name=* state=latest
    become: true

  - name: Ensure git is installed
    yum: name=git state=latest
    become: true

  - name: Checkout Project
    git:
       repo: https://github.com/xxxxxxxxxxx/fleetman-registry
       dest: /home/ec2-user/fleetman-registry/
       version: master

  - name: Prepare Maven Directory
    file:
       path: /opt
       state: directory
    become: true

  - name: Download Maven
    get_url:
       url: https://www.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
       dest: /opt/maven3.tar.gz
    become: true

  - name: Unpack Maven
    unarchive:
       remote_src: yes
       src: /opt/maven3.tar.gz
       dest: /opt/
    become: true

  - name: Set Mvn command
    alternatives:
       name: mvn
       path: /opt/apache-maven-3.3.9/bin/mvn
       link: /usr/bin/mvn
    become: true

  - name: Install JDK
    yum:
       name: java-1.8.0-openjdk-devel
       state: latest
    become: true

  - name: Use Java8 for Runtime Java
    alternatives:
       name: java
       path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
       link: /usr/bin/java
    become: true

  - name: Build the Executable (Using MVN, we could do this on Jenkins)
    command: mvn -DskipTests package
    args:
            chdir: fleetman-registry/
            creates: fleetman-registry/fleetman-registry-0.0.1-SNAPSHOT.jar

  - name: Build a link to the executable so it becomes a service
    file:
            src: /home/ec2-user/fleetman-registry/target/fleetman-registry-0.0.1-SNAPSHOT.jar
            dest: /etc/init.d/registry
            state: link
    become: true

  - name: Install Registry as a startup service. Logs available at /var/log/registry.log
    service:
            name: registry
            state: started
            enabled: yes
    become: true
